#/*****************************************************************************
# Assignment 1A
# FILENAME: Makefile
# AUTHOR:   Jason Feriante
# DATE:     25 Jan 2014
# 
# Usage: # shell% make
# 
# Email: feriante@wisc.edu
# Semester: CS537 Spring 2014
# Section: LEC 001
# Professor: Daniel Scott Myers
#****************************************************************************/
CC     = gcc
CFLAGS = -Wall -Werror

all: mysh

mysh:
	$(CC) -o mysh mysh.c $(CFLAGS)

clean:
	rm -rf mysh.c